#ifndef SOUNDIOPP_ENUMS_H
#define SOUNDIOPP_ENUMS_H
namespace sio
{
    enum class ErrorId {
        None = SoundIoErrorNone,
        NoMem = SoundIoErrorNoMem,
        InitAudioBackend = SoundIoErrorInitAudioBackend,
        SystemResources = SoundIoErrorSystemResources,
        OpeningDevice = SoundIoErrorOpeningDevice,
        NoSuchDevice = SoundIoErrorNoSuchDevice,
        Invalid = SoundIoErrorInvalid,
        BackendUnavailable = SoundIoErrorBackendUnavailable,
        Streaming = SoundIoErrorStreaming,
        IncompatibleDevice = SoundIoErrorIncompatibleDevice,
        NoSuchClient = SoundIoErrorNoSuchClient,
        IncompatibleBackend = SoundIoErrorIncompatibleBackend,
        BackendDisconnected = SoundIoErrorBackendDisconnected,
        Interrupted = SoundIoErrorInterrupted,
        Underflow = SoundIoErrorUnderflow,
        EncodingString = SoundIoErrorEncodingString
    };

    enum class ChannelId {
        Invalid = SoundIoChannelIdInvalid,
        FrontLeft = SoundIoChannelIdFrontLeft,
        FrontRight = SoundIoChannelIdFrontRight,
        FrontCenter = SoundIoChannelIdFrontCenter,
        Lfe = SoundIoChannelIdLfe,
        BackLeft = SoundIoChannelIdBackLeft,
        BackRight = SoundIoChannelIdBackRight,
        FrontLeftCenter = SoundIoChannelIdFrontLeftCenter,
        FrontRightCenter = SoundIoChannelIdFrontRightCenter,
        BackCenter = SoundIoChannelIdBackCenter,
        SideLeft = SoundIoChannelIdSideLeft,
        SideRight = SoundIoChannelIdSideRight,
        TopCenter = SoundIoChannelIdTopCenter,
        TopFrontLeft = SoundIoChannelIdTopFrontLeft,
        TopFrontCenter = SoundIoChannelIdTopFrontCenter,
        TopFrontRight = SoundIoChannelIdTopFrontRight,
        TopBackLeft = SoundIoChannelIdTopBackLeft,
        TopBackCenter = SoundIoChannelIdTopBackCenter,
        TopBackRight = SoundIoChannelIdTopBackRight,
        BackLeftCenter = SoundIoChannelIdBackLeftCenter,
        BackRightCenter = SoundIoChannelIdBackRightCenter,
        FrontLeftWide = SoundIoChannelIdFrontLeftWide,
        FrontRightWide = SoundIoChannelIdFrontRightWide,
        FrontLeftHigh = SoundIoChannelIdFrontLeftHigh,
        FrontCenterHigh = SoundIoChannelIdFrontCenterHigh,
        FrontRightHigh = SoundIoChannelIdFrontRightHigh,
        TopFrontLeftCenter = SoundIoChannelIdTopFrontLeftCenter,
        TopFrontRightCenter = SoundIoChannelIdTopFrontRightCenter,
        TopSideLeft = SoundIoChannelIdTopSideLeft,
        TopSideRight = SoundIoChannelIdTopSideRight,
        LeftLfe = SoundIoChannelIdLeftLfe,
        RightLfe = SoundIoChannelIdRightLfe,
        Lfe2 = SoundIoChannelIdLfe2,
        BottomCenter = SoundIoChannelIdBottomCenter,
        BottomLeftCenter = SoundIoChannelIdBottomLeftCenter,
        BottomRightCenter = SoundIoChannelIdBottomRightCenter,
        MsMid = SoundIoChannelIdMsMid,
        MsSide = SoundIoChannelIdMsSide,
        AmbisonicW = SoundIoChannelIdAmbisonicW,
        AmbisonicX = SoundIoChannelIdAmbisonicX,
        AmbisonicY = SoundIoChannelIdAmbisonicY,
        AmbisonicZ = SoundIoChannelIdAmbisonicZ,
        XyX = SoundIoChannelIdXyX,
        XyY = SoundIoChannelIdXyY,
        HeadphonesLeft = SoundIoChannelIdHeadphonesLeft,
        HeadphonesRight = SoundIoChannelIdHeadphonesRight,
        ClickTrack = SoundIoChannelIdClickTrack,
        ForeignLanguage = SoundIoChannelIdForeignLanguage,
        HearingImpaired = SoundIoChannelIdHearingImpaired,
        Narration = SoundIoChannelIdNarration,
        Haptic = SoundIoChannelIdHaptic,
        DialogCentricMix = SoundIoChannelIdDialogCentricMix,
        Aux = SoundIoChannelIdAux,
        Aux0 = SoundIoChannelIdAux0,
        Aux1 = SoundIoChannelIdAux1,
        Aux2 = SoundIoChannelIdAux2,
        Aux3 = SoundIoChannelIdAux3,
        Aux4 = SoundIoChannelIdAux4,
        Aux5 = SoundIoChannelIdAux5,
        Aux6 = SoundIoChannelIdAux6,
        Aux7 = SoundIoChannelIdAux7,
        Aux8 = SoundIoChannelIdAux8,
        Aux9 = SoundIoChannelIdAux9,
        Aux10 = SoundIoChannelIdAux10,
        Aux11 = SoundIoChannelIdAux11,
        Aux12 = SoundIoChannelIdAux12,
        Aux13 = SoundIoChannelIdAux13,
        Aux14 = SoundIoChannelIdAux14,
        Aux15 = SoundIoChannelIdAux15
    };

    enum class ChannelLayoutId {
        Mono = SoundIoChannelLayoutIdMono,
        Stereo = SoundIoChannelLayoutIdStereo,
        Sur2Point1 = SoundIoChannelLayoutId2Point1,
        Sur3Point0 = SoundIoChannelLayoutId3Point0,
        Sur3Point0Back = SoundIoChannelLayoutId3Point0Back,
        Sur3Point1 = SoundIoChannelLayoutId3Point1,
        Sur4Point0 = SoundIoChannelLayoutId4Point0,
        Quad = SoundIoChannelLayoutIdQuad,
        QuadSide = SoundIoChannelLayoutIdQuadSide,
        Sur4Point1 = SoundIoChannelLayoutId4Point1,
        Sur5Point0Back = SoundIoChannelLayoutId5Point0Back,
        Sur5Point0Side = SoundIoChannelLayoutId5Point0Side,
        Sur5Point1 = SoundIoChannelLayoutId5Point1,
        Sur5Point1Back = SoundIoChannelLayoutId5Point1Back,
        Sur6Point0Side = SoundIoChannelLayoutId6Point0Side,
        Sur6Point0Front = SoundIoChannelLayoutId6Point0Front,
        Hexagonal = SoundIoChannelLayoutIdHexagonal,
        Sur6Point1 = SoundIoChannelLayoutId6Point1,
        Sur6Point1Back = SoundIoChannelLayoutId6Point1Back,
        Sur6Point1Front = SoundIoChannelLayoutId6Point1Front,
        Sur7Point0 = SoundIoChannelLayoutId7Point0,
        Sur7Point0Front = SoundIoChannelLayoutId7Point0Front,
        Sur7Point1 = SoundIoChannelLayoutId7Point1,
        Sur7Point1Wide = SoundIoChannelLayoutId7Point1Wide,
        Sur7Point1WideBack = SoundIoChannelLayoutId7Point1WideBack,
        Octagonal = SoundIoChannelLayoutIdOctagonal
    };

    enum class BackendId {
        None = SoundIoBackendNone,
        Jack = SoundIoBackendJack,
        PulseAudio = SoundIoBackendPulseAudio,
        Alsa = SoundIoBackendAlsa,
        CoreAudio = SoundIoBackendCoreAudio,
        Wasapi = SoundIoBackendWasapi,
        Dummy = SoundIoBackendDummy
    };

    enum class DeviceAimId {
        Input = SoundIoDeviceAimInput,
        Output = SoundIoDeviceAimOutput
    };

    enum class FormatId {
        Invalid = SoundIoFormatInvalid,
        S8 = SoundIoFormatS8,
        U8 = SoundIoFormatU8,
        S16LE = SoundIoFormatS16LE,
        S16BE = SoundIoFormatS16BE,
        U16LE = SoundIoFormatU16LE,
        U16BE = SoundIoFormatU16BE,
        S24LE = SoundIoFormatS24LE,
        S24BE = SoundIoFormatS24BE,
        U24LE = SoundIoFormatU24LE,
        U24BE = SoundIoFormatU24BE,
        S32LE = SoundIoFormatS32LE,
        S32BE = SoundIoFormatS32BE,
        U32LE = SoundIoFormatU32LE,
        U32BE = SoundIoFormatU32BE,
        Float32LE = SoundIoFormatFloat32LE,
        Float32BE = SoundIoFormatFloat32BE,
        Float64LE = SoundIoFormatFloat64LE,
        Float64BE = SoundIoFormatFloat64BE
    };
}
#endif //SOUNDIO_ENUMS_H
